bobanetwork/gateway

package.json
Update Package Version to Sync with Latest release tag.
=> update: package version

package.json, yarn.lock
:clipboard: Add associated issues, tickets, docs URL here.
closes: 
Removed package web3 as we are not using it!
=> fix: removed unused packages

src/components/global/background/index.stories.tsx, src/components/global/svg/index.stories.tsx, src/selectors/networkSelector.js, src/selectors/setupSelector.js
This resolve the issue related to https://github.com/bobanetwork/gateway/issues/109
=> Gateway : Story Book broken with error. #109

src/hooks/useBridgeCleanup/index.test.tsx, src/hooks/useBridgeCleanup/index.ts
Hook structure has been remplace and unit test has been added
=> Hooks - useBridgeCleanup - unit tests

src/hooks/useInterval/index.test.tsx, src/hooks/useInterval/index.ts
Unit test for Callback on useInterval
Unit test for Change delay on useInterval
=> Hooks - useInterval- unit tests

cypress/e2e/helpers/base/page.ts, src/components/ApplicationBanner/data.tsx, src/components/global/button/index.tsx, src/components/global/button/types.ts, src/components/global/placeholderConnect/__snapshots__/index.test.tsx.snap, src/components/layout/Header/NavDrawer/styles.ts, src/components/listEarn/ListEarn.js, src/components/modal/Modal.tsx, src/components/modal/styles.ts, src/containers/home/__snapshots__/index.test.tsx.snap, src/hooks/useBridgeAlerts.ts
:clipboard:  closes: https://github.com/bobanetwork/gateway/issues/150
preparing for release
-  // disable stake button
-  // show tooltip _In preparation for the release of Boba Light Bridge, the earn program is being sunset. Stake has been disabled. Please remove your funds._
-  // add alert on 3rd bridge with proper message
-  // update banner copy
-  // remove close button
-  // fix color for close button on modal
- update broken unit test / integration test
=> Gateway: preparing for release.

src/components/layout/Header/feeSwitcher/__snapshots__/index.test.tsx.snap, src/components/layout/Header/feeSwitcher/index.test.tsx, src/components/layout/Header/feeSwitcher/index.tsx
:clipboard:  closes: https://github.com/bobanetwork/gateway/issues/94
Fix for switching fee to use for bridging.
- Fix for switching fee & test cases
=> fix : switch fee token issues with test cases

src/reducers/balanceReducer.ts, src/reducers/bridgeReducer.ts
Typing balance & bridge reducer.
=> fix: Type Balance & Bridge reducer

src/reducers/daoReducer.ts, src/reducers/dataReducer.ts
=> fix: Type Dao & Data reducer

readme.md, src/reducers/fixedReducer.ts, src/reducers/index.ts, src/reducers/loadingReducer.ts, src/reducers/loginReducer.ts
Typed index.js, index reducer, etc.
=> Fix: Type fixed index reducer

src/reducers/lookupReducer.ts, src/reducers/networkReducer.ts, src/reducers/nftReducer.ts, src/reducers/setupReducer.ts
fix: type lookup, network, nft and setupreducer
=> fix: type lookup, network, nft and setupreducer

src/reducers/signatureReducer.ts, src/reducers/tokenReducer.ts, src/reducers/transactionReducer.ts, src/reducers/uiReducer.ts, src/reducers/verifierReducer.ts
fix: Type sig, token, tx, ui, verifier reducer
=> fix: Type sig, token, tx, ui, verifier reducer

readme.md, src/components/copy/Copy.tsx, src/components/layout/Footer/SocialLinks/style.ts, src/containers/Bridging/BridgeInput/BridgeToAddress/index.test.tsx, src/containers/Bridging/__snapshots__/index.test.tsx.snap, src/containers/Bridging/chain/styles.ts, src/containers/earn/styles.ts, src/containers/home/__snapshots__/index.test.tsx.snap, src/containers/modals/dao/CastVoteModal.js, src/containers/modals/dao/DelegateDaoModal.js, src/containers/modals/dao/old/NewProposalModalOldDao.js, src/containers/modals/noMetaMask/InstallMetaMaskModal/styles.ts, src/containers/modals/stake/DepositStake.tsx, src/containers/modals/tokenPicker/styles.ts, src/containers/save/Save.styles.ts, src/services/networkService.ts, src/util/constant.ts
General cleanup
- removing unused code
- applying warnings
- etc.
=> fix: General gateway cleanup 

cypress/e2e/specs/flow/bridging.spec.cy.ts
:clipboard:  closes: #205 
Updates test to work with new flow.
- Follow correct flow in bridging test.
=> fixing bridging test to capture new flow

cypress/e2e/helpers/base/page.header.ts, cypress/e2e/specs/flow/connect.spec.cy.ts, src/assets/images/icons/copy.svg, src/assets/images/icons/disconnect.svg, src/components/global/dropdown/index.tsx, src/components/layout/Header/WalletAddress/index.tsx, src/components/layout/Header/WalletAddress/style.ts, src/components/layout/Header/feeSwitcher/index.tsx, src/components/layout/Header/feeSwitcher/styles.ts, src/containers/history/tests/__snapshots__/history.test.tsx.snap, src/containers/home/__snapshots__/index.test.tsx.snap
:clipboard:  closes: #32 
Fixes styling issues in the wallet address component in the site header
- Made styling changes to the wallet address component in the header
- Changed Wallet Address component to use dropdown component (`components/global/dropdown`)
- Refactored wallet svg icons
- made minor refactoring changes to global dropdown component
- updated end to end test 
n/a
=> Fixed styling for wallet address component, refactored

src/containers/history/TransactionsResolver.tsx, src/services/graphql.service.ts, src/services/networkService.ts, src/services/transaction.service.ts, src/util/network/config/arbitrum.ts, src/util/network/config/network-details.types.ts, src/util/network/config/optimism.ts, src/util/network/network.util.ts
https://github.com/bobanetwork/gateway/issues/225
https://github.com/bobanetwork/boba/issues/1287
https://github.com/bobanetwork/boba-aws-infrastructure/issues/70
We moved away from The Graph to GoldSky. Deployed LightBridge subgraphs and had to make associated changes. 
- Fix some minor issues
- Removed redundant code
- Refactoring to match GoldSky return values
- Replace endpoints in GraphQL service
Manual testing, history page returning correct information.
=> feat: History page for Light bridge working, couple of issues fixed, ..

cypress/e2e/helpers/base/page.ts, cypress/e2e/specs/layout.spec.cy.ts, src/components/ApplicationBanner/data.tsx, src/containers/home/__snapshots__/index.test.tsx.snap
- Adds deprecation banner to notify users about relayer deprecation
Local test
=> feat: Add Relayer deprecation banner

package.json, yarn.lock
Updated e2e tests dependencies
- Updated `@synthetixio/synpress` package to latest version
N/A
N/A
=> updated e2e test dependencies

cypress.config.ts, readme.md
Updates documentation. Removes unnecessary variable.
- Adds more description to the documentation
- Removes unnecessary variable in documentation and cypress test configuration file.
n/a
n/a
=> Fixes documentation. Removes unnecessary variable.

.github/workflows/coverage-linting.yml, package.json, yarn.lock
- dotenv
- sentry tracing
- preset-env
- Change 1
- Change 2
- ...
=> 🔨  package-updates:

.babelrc.json, package.json
- Downgrade dotenv
- change babel rc config.
- ...
=> ⚒️ : Downgrade dotenv / updated config for babel

src/services/graphql.service.ts, src/services/networkService.ts
Add DAO Subgraph endpoint.
- Url change/endpoint
- Adapt query
Local test
=> feat: Add Goldsky for DAO 

src/services/graphql.service.ts
=> feat: Add Goerli DAO Subgraph

package.json
=> 📦  version update

src/services/networkService.ts
Fix the the BNB connection failure.
=> 🔨  fix: bnb connect failure

src/components/global/background/styles.ts, src/containers/modals/tokenPicker/styles.ts
:clipboard:  closes: #329 
- Updated radial gradient in the background of the bridge page for light mode.
- Updated text color of token symbols in the token picker modal for light mode
=> fixed radial gradient and token text color

src/components/ApplicationBanner/__snapshots__/index.test.tsx.snap, src/components/ApplicationBanner/data.tsx, src/components/ApplicationBanner/index.tsx, src/components/ApplicationBanner/styles.ts, src/containers/home/__snapshots__/index.test.tsx.snap
:clipboard:  
closes: https://github.com/bobanetwork/gateway/issues/377
closes: https://github.com/bobanetwork/gateway/issues/361
Change for notification banner in carousel to slides for every 7 sec.
- Added banner for Goerli 2 deprecation
- Added carousel view for banner to slide through multiple banner with arrow buttons.
https://github.com/bobanetwork/gateway/assets/86316370/a42a34d4-b7a7-4c53-a20e-9dede77fb2b1
=> fix: carousel view for banner

src/containers/dao/OldDao.js, src/containers/dao/OldDao.styles.js, src/containers/modals/DaoModals/CastVoteModal/index.tsx, src/containers/modals/DaoModals/CastVoteModal/styles.ts, src/containers/modals/DaoModals/DelegateDaoModal/index.tsx, src/containers/modals/DaoModals/DelegateDaoModal/styles.ts, src/containers/modals/DaoModals/NewProposalModal/index.tsx
1. Make sure user can create proposal
2. Check for available votes (review contract)
3. check for available boba balance to create proposal
4. check for voting power to vote for proposal
5. validate proposal listing / creation / delegation of votes to self & other
6. validate casting of vote (against / for / obstain)
7. validate execute / queue proposal
8. Disable button on clicking action & show loading indicator
=> Dao Changes!

src/actions/createAction.ts, src/hooks/useGasWatcher.ts, src/services/networkService.ts
-  fix savings infinity view
- earli return if contract address invalid
- do no throw to sentry if tsx rejected!
=> change: Sentry Issues

src/actions/createAction.ts, src/containers/dao/OldDao.js, src/containers/home/__snapshots__/index.test.tsx.snap, src/containers/modals/DaoModals/CastVoteModal/index.tsx, src/containers/modals/DaoModals/NewProposalModal/index.tsx, src/containers/modals/DaoModals/NewProposalModal/types.ts, src/hooks/useBridge/index.test.tsx, src/hooks/useWalletConnect/index.test.tsx, src/services/graphql.service.ts, src/services/networkService.ts
Closes: https://github.com/bobanetwork/gateway/issues/365
- Sentry : refactored create action to handled the sentry logs better way
- Dao Execute, Queue with async handling
=> Sentry : refactored create action | Dao Execute, Queue with async handling

src/containers/home/__snapshots__/index.test.tsx.snap, src/containers/modals/MultiStepWithdrawalModal/VerticalStepper.tsx, src/services/anchorage.service.ts, src/services/graphql.service.ts, src/services/transaction.service.ts
:clipboard:  
closes: https://github.com/bobanetwork/gateway/issues/392
closes: https://github.com/bobanetwork/gateway/issues/404
- Close the modal and show the appropriate error to the user on failed tx instead of the claim button
- Pending withdrawal exits are missing. Those transactions I submitted the proof don't show up in the history tab.
- Deposit transactions are missing.
=> ⚒️  Fix : Sepolia Issue Review

src/containers/Bridging/BridgeTypeSelector/__snapshots__/index.test.tsx.snap, src/containers/Bridging/BridgeTypeSelector/index.test.tsx, src/containers/Bridging/BridgeTypeSelector/index.tsx, src/containers/Bridging/__snapshots__/index.test.tsx.snap, src/containers/Bridging/tests/__snapshots__/BridgeTypeSelector.test.tsx.snap, src/hooks/useBridge/index.test.tsx, src/hooks/useBridge/index.ts, src/services/networkService.ts
- Enabled light bridge on mainnet (hiding fast bridging)
- Minor refactoring
Merge once we want to go live with light bridge (everything ready aside from liquidity). 
@toser2
=> feat: Enable light bridge on mainnet

src/components/notificationBanner/bannerConfig.ts, src/containers/Bridging/BridgeTypeSelector/index.tsx, src/containers/Bridging/index.tsx, src/containers/home/__snapshots__/index.test.tsx.snap, src/containers/modals/MultiStepWithdrawalModal/VerticalStepper.tsx, src/services/transaction.service.ts
- Add notification banner about anchorage update with disabling classic withdrawal for 10 day.
```
Note: Classic withdrawals will be temporarily suspended for a duration of 10 days beginning 
April 6th in preparation for our Anchorage update! Light bridging will remain available
throughout the period.
```
=> 🔔  Banner : Temporary suspension of classic withdrawal

package.json
=> Prepare Release  package version

src/containers/history/constants.ts, src/util/network/network.util.ts
- Shows Optimism/Arbitrum on Gateway mainnet
=> fix: Op/Arb show on Mainnet

src/services/transaction.service.ts
=> fix: Additional network config for limited networks (OP/ARB) in History

src/components/ApplicationBanner/index.tsx
:clipboard:  
closes: https://github.com/bobanetwork/gateway/issues/446
Remove blank banner slide in case banner is closed by user.
- Fix blank banner issue.
=> ⚒️  Blank banner fix.

package.json
Package Update for fix with routes!
=> package update

src/components/layout/Header/styles.ts, src/containers/history/History.tsx, src/containers/home/__snapshots__/index.test.tsx.snap, src/containers/modals/stake/DepositStake.tsx, src/containers/save/Save.tsx, src/services/networkService.ts, src/services/transaction.service.ts
=> Gateway : Fix/stake page not working

package.json
=> 📦 Stake Page Fixes.

package.json, src/containers/modals/BridgeConfirmModal/index.tsx, src/containers/modals/MultiStepWithdrawalModal/VerticalStepper.tsx, src/util/dates.ts, yarn.lock
Anchorage
- fix date format in case of checking for date to enable proof button.
- fix currency format with float of 4.
- fix add check to disable proof on initiation of txs.
=> Chore: Anchorage fixes.

src/actions/uiAction.ts, src/components/listProposal/listProposal.js, src/containers/Bridging/BridgeAction/index.tsx, src/containers/Bridging/BridgeHeader/index.tsx, src/containers/Bridging/BridgeInput/index.tsx, src/containers/Bridging/chain/index.tsx, src/containers/Bridging/index.tsx, src/containers/dao/OldDao.js, src/containers/earn/earnList/earnListItem/index.tsx, src/containers/history/TransactionsResolver.tsx, src/containers/modals/MultiStepWithdrawalModal/VerticalStepper.tsx, src/containers/modals/MultiStepWithdrawalModal/index.tsx, src/containers/modals/earn/EarnWithdrawConfirmModal/index.tsx, src/containers/modals/earn/index.tsx, src/containers/modals/index.tsx, src/containers/modals/noMetaMask/NoMetaMaskModal.tsx, src/containers/save/Save.tsx, src/hooks/useBridge/index.ts, src/hooks/useSwitchChain/index.ts, src/hooks/useWalletConnect/index.ts, src/hooks/useWalletSwitch/index.ts, src/reducers/uiReducer.ts, src/services/wallet.service.ts
Change:
---
1. Refactored open modal function
2. Fix state conflict with pending withdrawal and new withdrawal initiation.
3. Fix amount parse with correct decimal to fix the USDT issues.
=> Gateway: Fixes & Cleanup

src/actions/networkAction.ts, src/containers/history/History.tsx, src/containers/modals/MultiStepWithdrawalModal/index.tsx, src/containers/modals/tokenPicker/TokenPickerModal.tsx, src/hooks/useAmountToReceive/index.ts, src/hooks/useBridgeAlerts/index.ts, src/services/networkService.ts
Change
--- 
- USDT Amount conversion while representing.
- Clean up dead code.
=> ⚒️ Fix USDT Conversion issues 

src/containers/modals/MultiStepWithdrawalModal/VerticalStepper.tsx, src/containers/modals/MultiStepWithdrawalModal/config.ts, src/hooks/useBridgeAlerts/index.ts, src/hooks/useBridgeSetup/index.ts, src/services/networkService.ts
=> Update Copy Proove page with crash fixes.

package.json, src/containers/modals/MultiStepWithdrawalModal/VerticalStepper.tsx
=> Package Version Update!

package.json, src/containers/modals/MultiStepWithdrawalModal/index.tsx
=> Fix: updated package version with notes

src/services/networkService.ts
Fix: for crash on OMG token which is not supported on sepolia testnet.
=> fix for OMG check before checking for L1 on approve erc 20

.github/workflows/coverage-linting.yml, src/containers/earn/earnList/__snapshots__/index.test.tsx.snap, src/containers/earn/earnList/earnListItem/__snapshots__/index.test.tsx.snap, src/containers/home/__snapshots__/index.test.tsx.snap, src/services/wallet.service.ts, src/util/amountConvert.ts
- current function of formatting the large number is incorrectly formatting the value below 0.
- type fixed for wallet connect init.
As currently ETH balance in pool is. 0.093ETH.
https://etherscan.io/address/0x1A26ef6575B7BBB864d984D9255C069F6c361a14
=> Earn page: Incorrect PoolBalance View fixes

src/services/networkService.ts
@sk-enya fixes the issue you mentioned on slack.
=> fix: token balance check

.github/workflows/end2end-test.yml, e2e-tests/lib/gatewayAction.ts, e2e-tests/package.json, e2e-tests/pages/basePage.ts, e2e-tests/pages/bridgePage.ts, e2e-tests/tests/bridging.spec.ts, package.json, src/actions/networkAction.ts, src/containers/modals/tokenPicker/TokenPickerModal.tsx, src/hooks/useBridge/index.test.tsx, src/hooks/useBridge/index.ts, src/hooks/useBridgeSetup/index.test.tsx, src/services/mock/teleporation.ts, src/services/networkService.ts, src/services/teleportation.service.test.ts, src/services/teleportation.service.ts, src/services/transaction.service.ts, src/util/network/config/bnb.ts, src/util/network/network.util.ts, yarn.lock
=> Fix: Light bridging withdrawal & Deposit fixes

buildspec.yml
=> Fix: code build aws script

src/components/ApplicationBanner/__snapshots__/index.test.tsx.snap, src/components/NetworkSelector/__snapshots__/index.test.tsx.snap, src/components/bridge/NetworkPickerList/tests/__snapshots__/networkPickerList.test.tsx.snap, src/components/global/placeholderConnect/__snapshots__/index.test.tsx.snap, src/components/global/typography/__snapshots__/index.test.tsx.snap, src/components/layout/Footer/GasWatcher/__snapshots__/index.test.tsx.snap, src/components/layout/Header/Navigation/index.test.tsx, src/components/layout/Header/index.test.tsx, src/components/layout/PageTitle/__snapshots__/index.test.tsx.snap, src/components/notificationBanner/tests/__snapshots__/index.test.tsx.snap, src/containers/Bridging/BridgeInput/BridgeToAddress/__snapshots__/index.test.tsx.snap, src/containers/Bridging/ThirdPartyBridges/__snapshots__/index.test.tsx.snap, src/containers/Bridging/__snapshots__/index.test.tsx.snap, src/containers/earn/__snapshots__/Earn.test.tsx.snap, src/containers/earn/earnList/__snapshots__/index.test.tsx.snap, src/containers/earn/earnList/earnListItem/__snapshots__/index.test.tsx.snap, src/containers/history/tests/__snapshots__/history.test.tsx.snap, src/containers/home/__snapshots__/index.test.tsx.snap
=> fix broken test

src/containers/Trade/index.tsx, src/hooks/UseFetchItems/index.tsx
- Reduce caching to 1day 
- Trade icon fix light on dark and dark on light background.
=> reduce cache to 1day and image light on dark and vv

.github/CODEOWNERS
=> updated code owners

src/containers/Ecosystem/index.tsx, src/containers/Trade/index.tsx
=> updated key and accessibility

src/components/cardList/styles.ts
fix card height in case of single card
=> fix card height in case of single card

.env.example, readme.md, src/components/global/button/__snapshots__/index.test.tsx.snap, src/components/global/button/styles.ts, src/containers/Bridging/BridgeAction/__snapshots__/index.test.tsx.snap, src/containers/Bridging/BridgeAction/index.tsx, src/util/analytics.ts, src/util/constant.ts
On ramp integration button with link to onramp.network url.
=> Added button on bridge page to purchase token updated env var

package.json, src/services/transaction.service.ts, yarn.lock
Updated the graphql utils function calls!
- fix to show the correct status of transaction on UI
=> fix for query narrowing to avoid the status pending always

package.json
=> release preperation

.env.example, package.json, readme.md, src/components/SentryWrapper/SentryWrapper.tsx, src/components/global/button/__snapshots__/index.test.tsx.snap, src/components/global/button/styles.ts, src/containers/Bridging/BridgeAction/__snapshots__/index.test.tsx.snap, src/containers/Bridging/BridgeAction/index.tsx, src/services/transaction.service.ts, src/util/analytics.ts, src/util/constant.ts, yarn.lock
- Update the axios module.
- Fix the querying data on history page for light bridge transaction from Boba => Eth
=> Gateway: Release changes.
